//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.26 at 11:41:27 AM MSK 
//


package ml.pevgen.demows.web.soap.recon;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ml.pevgen.demows.web.soap.recon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fault_QNAME = new QName("http://xbank.ru/soa/service/sudir/itdi/smallsystem.generic.supportingdata.reconciliation/2.0.0", "fault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ml.pevgen.demows.web.soap.recon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericSupportingDataReconciliationException }
     * 
     */
    public GenericSupportingDataReconciliationException createGenericSupportingDataReconciliationException() {
        return new GenericSupportingDataReconciliationException();
    }

    /**
     * Create an instance of {@link GetSupportingData }
     * 
     */
    public GetSupportingData createGetSupportingData() {
        return new GetSupportingData();
    }

    /**
     * Create an instance of {@link GetSupportingDataResponse }
     * 
     */
    public GetSupportingDataResponse createGetSupportingDataResponse() {
        return new GetSupportingDataResponse();
    }

    /**
     * Create an instance of {@link GenericSupportingDataObject }
     * 
     */
    public GenericSupportingDataObject createGenericSupportingDataObject() {
        return new GenericSupportingDataObject();
    }

    /**
     * Create an instance of {@link ComplexTest }
     * 
     */
    public ComplexTest createComplexTest() {
        return new ComplexTest();
    }

    /**
     * Create an instance of {@link ComplexTestResponse }
     * 
     */
    public ComplexTestResponse createComplexTestResponse() {
        return new ComplexTestResponse();
    }

    /**
     * Create an instance of {@link GenericAttribute }
     * 
     */
    public GenericAttribute createGenericAttribute() {
        return new GenericAttribute();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericSupportingDataReconciliationException }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GenericSupportingDataReconciliationException }{@code >}
     */
    @XmlElementDecl(namespace = "http://xbank.ru/soa/service/sudir/itdi/smallsystem.generic.supportingdata.reconciliation/2.0.0", name = "fault")
    public JAXBElement<GenericSupportingDataReconciliationException> createFault(GenericSupportingDataReconciliationException value) {
        return new JAXBElement<GenericSupportingDataReconciliationException>(_Fault_QNAME, GenericSupportingDataReconciliationException.class, null, value);
    }

}
