//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.26 at 11:41:27 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xbank.ru/soa/service/sudir/itdi/smallsystem.generic.supportingdata.reconciliation/2.0.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ml.pevgen.demows.web.soap.recon;
