//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.26 at 11:40:11 AM MSK 
//


package ml.pevgen.demows.web.soap.am;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="validatePasswordReturn" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validatePasswordReturn"
})
@XmlRootElement(name = "validatePasswordResponse")
public class ValidatePasswordResponse {

    protected boolean validatePasswordReturn;

    /**
     * Gets the value of the validatePasswordReturn property.
     * 
     */
    public boolean isValidatePasswordReturn() {
        return validatePasswordReturn;
    }

    /**
     * Sets the value of the validatePasswordReturn property.
     * 
     */
    public void setValidatePasswordReturn(boolean value) {
        this.validatePasswordReturn = value;
    }

}
